### ISSUE TITLE
Bug: Astroid hanging when toggling action on too much mail

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#161]
Select a ton of email, do something with it (like marking them unread): astroid will hang.

Here's the screenshot of what happens and then the debug output:

![capture d ecran de 2016-06-18 16-16-16](https://cloud.githubusercontent.com/assets/1629771/16171476/17a3143a-3570-11e6-9ea9-b7413d1ef327.png)

Debut: https://paste.cat/0a41N1

(Apparently, the action did work in this case the messages were properly marked as unread when looking at them again after restarting astroid because it freezed)

**Comment by gauteh** [comment]
Try latest master, I made the locking on the emitter a little less
restrictive and made refresh_stats run fewer unnecessary times.

**Comment by hugoroy** [comment]
Same issue.

**Comment by hugoroy** [comment]
Here's another way to reproduce something similar (probably the same issue):

1. Search for unread messages (example : tag:spam and tag:unread)
2. Mark as Read all messages by just keeping N pushed

Astroid hangs.

```



















[info ] (11:40:22): db: open db read-write.
[debug] (11:40:22): db: rw-s: waiting for rw lock.. (r-o open: 0)
[debug] (11:40:22): db: rw-s lock acquired.
[debug] (11:40:22): db: open time: 0.531 ms.
[debug] (11:40:22): toggle_action: threadid:00000000000212e3, add: remove: unread, 
[debug] (11:40:22): nm (00000000000212e3): remove tag: unread
[info ] (11:40:22): db: closing db.
[debug] (11:40:22): db: rw: releasing lock.
[debug] (11:40:22): db: rw-s: releasing lock.
[info ] (11:40:22): db: open db read-only, waiting for lock..
[debug] (11:40:22): db: read-only got lock.
[debug] (11:40:22): db: open time: 0.277 ms.
[info ] (11:40:22): actions: emitted updated and changed signal for thread: 00000000000212e3
[info ] (11:40:22): ql (0): tag:inbox, got changed thread signal: 00000000000212e3
[debug] (11:40:22): db: checking if thread: 00000000000212e3 matches query: tag:inbox
[debug] (11:40:22): db: thread in query check: 0.341 ms.
[debug] (11:40:22): ql: updated: did not find thread, time used: 1.146 ms.
[info ] (11:40:22): ql (1): tag:flagged, got changed thread signal: 00000000000212e3
[debug] (11:40:22): db: checking if thread: 00000000000212e3 matches query: tag:flagged
[debug] (11:40:22): db: thread in query check: 0.232 ms.
[debug] (11:40:22): ql: updated: did not find thread, time used: 0.332 ms.
[info ] (11:40:22): ql (2): tag:draft OR tag:waiting, got changed thread signal: 00000000000212e3
[debug] (11:40:22): db: checking if thread: 00000000000212e3 matches query: tag:draft OR tag:waiting
[debug] (11:40:22): db: thread in query check: 0.25 ms.
[debug] (11:40:22): ql: updated: did not find thread, time used: 0.35 ms.
[info ] (11:40:22): ql (3): date:last_month..today NOT tag:inbox NOT tag:archives, got changed thread signal: 00000000000212e3
[debug] (11:40:22): db: checking if thread: 00000000000212e3 matches query: date:last_month..today NOT tag:inbox NOT tag:archives
[debug] (11:40:22): db: thread in query check: 0.333 ms.
[debug] (11:40:22): ql: updated: did not find thread, time used: 6.34 ms.
[info ] (11:40:22): ql (4): tag:spam and tag:unread, got changed thread signal: 00000000000212e3
[debug] (11:40:22): db: checking if thread: 00000000000212e3 matches query: tag:spam and tag:unread
[debug] (11:40:22): db: thread in query check: 0.213 ms.
[debug] (11:40:22): ql: updated: found thread in: 0.265 ms.
[debug] (11:40:22): ql: deleted
[info ] (11:40:22): db: closing db.
[debug] (11:40:22): db: ro: waiting for lock to close..
[debug] (11:40:22): db: ro: closing..
[debug] (11:40:22): ql: refresh stats..
[info ] (11:40:22): db: open db read-only, waiting for lock..
[debug] (11:40:22): db: read-only got lock.
[debug] (11:40:22): db: open time: 0.193 ms.
[info ] (11:40:22): db: closing db.
[debug] (11:40:22): db: ro: waiting for lock to close..
[debug] (11:40:22): db: ro: closing..
[debug] (11:40:22): ti: got refresh stats.
[info ] (11:40:22): db: open db read-write.
[debug] (11:40:22): db: rw-s: waiting for rw lock.. (r-o open: 0)
[debug] (11:40:22): db: rw-s lock acquired.
[debug] (11:40:22): db: open time: 1.059 ms.
[debug] (11:40:22): toggle_action: threadid:00000000000212e2, add: remove: unread, 
[debug] (11:40:22): nm (00000000000212e2): remove tag: unread
[info ] (11:40:23): db: closing db.
[debug] (11:40:23): db: rw: releasing lock.
[debug] (11:40:23): db: rw-s: releasing lock.
[info ] (11:40:23): db: open db read-write.
[debug] (11:40:23): db: rw-s: waiting for rw lock.. (r-o open: 0)
[debug] (11:40:23): db: rw-s lock acquired.
[info ] (11:40:23): db: open db read-only, waiting for lock..
[debug] (11:40:23): db: open time: 1.059 ms.
[debug] (11:40:23): toggle_action: threadid:00000000000212e2, add: unread, remove: 
[debug] (11:40:23): nm (00000000000212e2): add tag: unread
[info ] (11:40:23): db: closing db.
[debug] (11:40:23): db: rw: releasing lock.
[debug] (11:40:23): db: rw-s: releasing lock.
[debug] (11:40:23): db: read-only got lock.
[debug] (11:40:23): db: open time: 5.521 ms.
[info ] (11:40:23): actions: emitted updated and changed signal for thread: 00000000000212e2
[info ] (11:40:23): ql (0): tag:inbox, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:inbox
[debug] (11:40:23): db: thread in query check: 0.342 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 1.23 ms.
[info ] (11:40:23): ql (1): tag:flagged, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:flagged
[debug] (11:40:23): db: thread in query check: 0.251 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 0.363 ms.
[info ] (11:40:23): ql (2): tag:draft OR tag:waiting, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:draft OR tag:waiting
[debug] (11:40:23): db: thread in query check: 0.267 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 0.38 ms.
[info ] (11:40:23): ql (3): date:last_month..today NOT tag:inbox NOT tag:archives, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: date:last_month..today NOT tag:inbox NOT tag:archives
[debug] (11:40:23): db: thread in query check: 0.407 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 7.639 ms.
[info ] (11:40:23): ql (4): tag:spam and tag:unread, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:spam and tag:unread
[debug] (11:40:23): db: thread in query check: 0.37 ms.
[debug] (11:40:23): ql: updated: found thread in: 0.45 ms.
[debug] (11:40:23): ql: updated
[info ] (11:40:23): actions: emitted updated and changed signal for thread: 00000000000212e2
[info ] (11:40:23): ql (0): tag:inbox, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:inbox
[debug] (11:40:23): db: thread in query check: 0.267 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 1.027 ms.
[info ] (11:40:23): ql (1): tag:flagged, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:flagged
[debug] (11:40:23): db: thread in query check: 0.229 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 0.338 ms.
[info ] (11:40:23): ql (2): tag:draft OR tag:waiting, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:draft OR tag:waiting
[debug] (11:40:23): db: thread in query check: 0.252 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 0.357 ms.
[info ] (11:40:23): ql (3): date:last_month..today NOT tag:inbox NOT tag:archives, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: date:last_month..today NOT tag:inbox NOT tag:archives
[debug] (11:40:23): db: thread in query check: 0.333 ms.
[debug] (11:40:23): ql: updated: did not find thread, time used: 6.567 ms.
[info ] (11:40:23): ql (4): tag:spam and tag:unread, got changed thread signal: 00000000000212e2
[debug] (11:40:23): db: checking if thread: 00000000000212e2 matches query: tag:spam and tag:unread
[debug] (11:40:23): db: thread in query check: 0.317 ms.
[debug] (11:40:23): ql: updated: found thread in: 0.383 ms.
[debug] (11:40:23): ql: updated
[info ] (11:40:23): db: closing db.
[debug] (11:40:23): db: ro: waiting for lock to close..
[debug] (11:40:23): db: ro: closing..
[info ] (11:40:23): db: open db read-write.
[debug] (11:40:23): db: rw-s: waiting for rw lock.. (r-o open: 0)
[debug] (11:40:23): db: rw-s lock acquired.
[info ] (11:40:23): db: open db read-only, waiting for lock..
[debug] (11:40:23): db: open time: 0.68 ms.
[debug] (11:40:23): toggle_action: threadid:00000000000212e2, add: remove: unread, 
[debug] (11:40:23): nm (00000000000212e2): remove tag: unread
[info ] (11:40:23): db: closing db.
[debug] (11:40:23): db: rw: releasing lock.
[debug] (11:40:23): db: rw-s: releasing lock.
[info ] (11:40:23): db: open db read-write.
[debug] (11:40:23): db: rw-s: waiting for rw lock.. (r-o open: 1)
[debug] (11:40:23): db: read-only got lock.
[debug] (11:40:23): db: open time: 4.184 ms.
[1]    3057 killed     astroid
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %                                                                                                                                                                            :(
137 hugo@xps ~ %       
```

**Comment by gauteh** [comment]
I pushed a locking / notifying change to master and crypto-2, this might
be the issue.

**Comment by hugoroy** [comment]
Still the same issue with the v0.6.

**Comment by gauteh** [comment]
Please try again, i fixed two locking issues, one in the logging, one in
the emitter of actions.

**Comment by hugoroy** [comment]
↪ août 8, 2016 2:12 — Gaute Hope:
> 
> Please try again, i fixed two locking issues, one in the logging, one in
> the emitter of actions.

It looks like this fixed it for me.

Astroid does not freeze any more when an operation is done on many many threads. @Taziden can you still reproduce the bug?

**Comment by taziden** [comment]
Nope. Seems fixed.

**Comment by gauteh** [comment]
Closing :beers:
