### ISSUE TITLE
--disable-plugins does not compile

### ISSUE THREAD

**Issue by teto** [astroidmail/astroid#223]
Hi,
I've been able to compile astroid after a few quirks.
First there is https://github.com/astroidmail/astroid/issues/211thus I have to run `scons --disable-plugins` but this disables gobject-introspection search I think due to this part in Sconstruct:
`
if disable_plugins:
  print "warning: plugins are disabled."
  env.AppendUnique (CPPFLAGS = [ '-DDISABLE_PLUGINS' ])

else:
  if not conf.CheckPKG('gobject-introspection-1.0'):
    print 'gobject-introspection-1.0 not found.'
    Exit (1)
`

A log where it can't find the proper headers
```

 scons --verbose --disable-plugins                                                                 
scons: Reading SConscript files ...
building version v0.6-82-gfaf14830 (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for C library libsass... (cached) no
Checking for C library libsass... (cached) yes
warning: plugins are disabled.
Checking for C library notmuch... yes
Checking for C function notmuch_database_get_revision..yes
Checking for C function notmuch_query_search_threads_st..yes
Checking for C function notmuch_query_count_threads_st..yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_system... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_log_setup... yes
Checking for C++ library boost_log... yes
Checking for C++ library boost_thread... yes
Checking for C++ library boost_date_time... yes
writing src/build_config.hh..
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/main.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/main.cc
g++ -o src/account_manager.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/account_manager.cc
g++ -o src/astroid.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/astroid.cc
g++ -o src/chunk.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/chunk.cc
g++ -o src/command_bar.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/command_bar.cc
g++ -o src/compose_message.o -c -std=c++11 -pthread -DSASSCTX_CONTEXT_H -DDISABLE_PLUGINS -DHAVE_NOTMUCH_GET_REV -DHAVE_QUERY_THREADS_ST -DHAVE_QUERY_COUNT_THREADS_ST -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gmime-2.6 -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -Isrc src/compose_message.cc
In file included from /usr/include/libpeas/peas-engine.h:27:0,
                 from /usr/include/libpeas/peas-autocleanups.h:26,
                 from /usr/include/libpeas/peas.h:24,
                 from src/plugin/manager.hh:3,
                 from src/compose_message.cc:22:
/usr/include/libpeas/peas-extension.h:26:26: fatal error: girepository.h: No such file or directory
compilation terminated.
scons: *** [src/compose_message.o] Error 1
scons: building terminated because of errors.
scons --verbose --disable-plugins  31,62s user 2,16s system 97% cpu 34,548 total
```

Even though gobject introspection is available and I can compile with 
`CFLAGS="-I/usr/include/gobject-introspection-1.0" scons  --disable-plugins`

```
$ pkg-config --libs --cflags libpeas-1.0                                                                            
-pthread -I/usr/include/libpeas-1.0 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0
```

**Comment by gauteh** [comment]
Please try the latest master, I pushed some changes for
--disable-plugin. I also pushed some changes for gobject-introspection
so it might work without plugins as well.

**Comment by teto** [comment]
Still fails
```

scons --no-cache --disable-plugins                                                                    
scons: Reading SConscript files ...
building version v0.6-83-gc4981117 (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for C library libsass... (cached) no
Checking for C library libsass... (cached) yes
warning: plugins are disabled.
Checking for C library notmuch... (cached) yes
Checking for C function notmuch_database_get_revision..(cached) yes
Checking for C function notmuch_query_search_threads_st..(cached) yes
Checking for C function notmuch_query_count_threads_st..(cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..
scons: done reading SConscript files.
scons: Building targets ...
compiling ==> src/compose_message.cc
In file included from src/compose_message.cc:22:0:
src/plugin/manager.hh:3:27: fatal error: libpeas/peas.h: No such file or directory
compilation terminated.
scons: *** [src/compose_message.o] Error 1
scons: building terminated because of errors.
```
It seems to me ubuntu's scons is broken. even when adding --no-cache, it answers from the cache :/
also it always rebuilds from scratch. Which version do your run ?
```
 scons -v 
SCons by Steven Knight et al.:
	script: v2.4.1.rel_2.4.1:3453:73fefd3ea0b0, 2015/11/09 03:25:05, by bdbaddog on ubuntu1404-32bit
	engine: v2.4.1.rel_2.4.1:3453:73fefd3ea0b0, 2015/11/09 03:25:05, by bdbaddog on ubuntu1404-32bit
	engine path: ['/usr/lib/scons/SCons']
Copyright (c) 2001 - 2015 The SCons Foundation

```

I've tried "rm -Rf .scon*" and relaunched the command:
```
scons: Reading SConscript files ...
building version v0.6-83-gc4981117 (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for C library libsass... no
Checking for C library libsass... no
libsass must be installed: could not find header file. you can disable libsass with --disable-libsass, however, that requires a SCSS compiler like 'sassc'.
```
but libsass is installed:
```
$ pkg-config --cflags --libs libsass
-lsass
```

**Comment by gauteh** [comment]
Sorry, my bad, I forgot to push the latest change. Please try again
(both with and without plugins).

Matthieu Coudron writes on oktober 12, 2016 22:51:

**Comment by teto** [comment]
it now works ty
